# Generated by Django 4.2.7 on 2023-11-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='main_app/static/facilityImg')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roomType', models.CharField(choices=[('1', 'Single Room'), ('2', 'Double Room'), ('3', 'Shared Room'), ('4', 'Studio'), ('5', 'Suite'), ('6', 'Guest House'), ('7', 'Duplex')], default='1', max_length=1)),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads')),
                ('size', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('facilities', models.ManyToManyField(to='main_app.facility')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomImages', models.ImageField(default='', upload_to='main_app/static/roomImg')),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('RENTER', 'Renter')], max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
      
    ]
