# Generated by Django 4.2.7 on 2023-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(choices=[('1', 'Sigle Room'), ('2', 'Double Room'), ('3', 'Shared Room'), ('4', 'Studio'), ('5', 'Suite'), ('6', 'Guest House'), ('7', 'Duplex')], default='1', max_length=1),
        ),
    ]
